version: 2
workflows:
  version: 2
  build:
    jobs:
    - verify: {}
jobs:
  verify:
    description: Runs simple or blue/green deployments to Cloud Foundry.
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - restore_cache:
        keys:
        - source-V1-{{ .Branch }}-{{ .Revision }}
        - source-V1-{{ .Branch }}
        - source-V1-
    - checkout
    - save_cache:
        key: source-V1-{{ .Branch }}-{{ .Revision }}
        paths:
        - .git
    - restore_cache:
        keys:
        - maven-repo-V1-{{ checksum "pom.xml" }}
        - maven-repo-V1
    - run:
        command: mvn dependency:go-offline
    - run:
        name: Maven Verify
        command: mvn verify -B
    - save_cache:
        paths:
        - ~/.m2
        key: maven-repo-V1-{{ checksum "pom.xml" }}
    - store_test_results:
        path: target/surefire-reports
    - store_test_results:
        path: target/failsafe-reports
    - run:
        name: Move deployable to storage
        command: |
          ARTIFACT=$(mvn -q exec:exec -Dexec.executable='echo' -Dexec.args='${project.build.directory}/${project.build.finalName}.${project.packaging}')
          mkdir artifacts
          mv $ARTIFACT artifacts/
    - store_artifacts:
        path: artifacts/
